FROM debian:10.8

RUN echo "deb http://ftp.de.debian.org/debian sid main" >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y cadvisor prometheus-squid-exporter prometheus-mongodb-exporter && rm -rf /var/lib/apt/lists/*
COPY startbind.sh ~/startbind.sh

EXPOSE 8080/tcp
EXPOSE 9001/tcp
EXPOSE 9301/tcp


ENTRYPOINT ["/bin/sh","~/startbind.sh"]